spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    database: h2
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: schema.sql