spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      schema-locations: schema.sql