spring:
  data:
    mongodb:
      host: localhost
      port: 28017
      database: admin
      password: example
      username: root
      authentication-database: admin
mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local