version: '3'

services:
  db:
    image: "postgres:12"
    container_name: db
    ports:
      - "5430:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=usr
      - POSTGRES_DB=testdb
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M